theme: minima
title: Rom&Ko Projects
author: H. Reed Romanko
email: hromanko@bu.edu

description: > # this means to ignore newlines until "baseurl:"
  This will be the nesting place of my projects, their components, data, and the scripts used in their conception.

# social links
linkedin_username: reed-romanko-9b38b5160 # DO NOT include the @ character, or else the build will fail!
github_username:  ReedRomanko # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
